public With Sharing class Account_Service{
    /*
    public static void updateNumberOfContacts(Set<Id> accountIds){   
         AccountsSelector accountSelector = (AccountsSelector) Application.selector.newInstance(Account.SObjectType);    
         List<Account>  accrec = accountSelector.selectContactswithAccount(accountIds);    
         fflib_ISObjectUnitOfWork unitOfWork = Application.UOW.newInstance();    
         Accounts domain = (accounts) new accounts.Constructor().construct(accrec);    
         List<Account>  accountstoregister = domain.setNumberofContacts();
         if (!accountstoregister.isEmpty()) {
             unitofwork.registerDirty(accountstoregister);
             unitOfWork.commitWork();
        }
    }
*/
}