public class EmployeHelper 
{
    public static void list1()
    {
       map<string , String >  fr =new map<String , string>();
        fr.put('red ','Apple');
	fr.Put('Yellow','Banana');
	fr.Put('Orange','Orange');
	fr.Put('Black','Grapes');
	fr.Put('Green','Grapes');
        
        
        
        system.debug(fr.size());
        fr.put('red','apple');
        system.debug(fr.size());
        
        
        
        
        
        
        
        
        
        
        
    }

}