public class EmployeeHelper 
{
   public Integer employeeCode , employeeage ;
   public String  employeeName ,contactNumber ,designation ,emailaddress ,companyName ,Location;
   public Decimal currentCTC;
   public Date birthDate ,joiningDate;
   public Boolean isActive;
   /*  eHelper.employeeCode =3738292;
          eHelper.employeename = 'bablu';
            eHelper.employeeage = 23;
           eHelper.designation = 'Senior Developer';

system.debug(eHelper.employeeCode);
system.debug(eHelper.employeename);
system.debug(eHelper.employeeage);
system.debug(eHelper.designation);
*/
}